version: '3.9'

services:
    api:
        build:
            dockerfile: /PrometheusDotNetPOC/Dockerfile 
            context: PrometheusDotNetPOC
        ports:
            - 8080:80

    prometheus:
        image: prom/prometheus:latest
        command: ["--config.file=/prometheus-config/prometheus-scrape.yml"]
        volumes:
            - ./prometheus-config:/prometheus-config
            - ./data/prometheus:/prometheus
        ports:
            - 9090:9090